### ISSUE TITLE
Проверить / улучшить код для приема сигнала

### ISSUE THREAD

**Issue by RodionGork** [el-pths/nosov-dsp#2]
Воспользоваться примером программы, получающей сигнал с аудиовхода:

https://github.com/el-pths/nosov-dsp/blob/master/examples/SoundCatcher.java

Скомпилировать, протестировать (например, с микрофоном или другим аудиоустройством), определить значение амплитуды, отображаемое программой при отсутствии и присутствии звука, шума (свиста, хлопков). В случае если разница не наблюдается, попытаться исследовать и модифицировать код для достижения нужного эффекта.

Результаты записать в комментарии ниже.

**Comment by NosovMihail** [comment]
Встроенный в ноутбук микрофон программа не воспринимает, подключенный отдельно микрофон оно слышит. В тишине выдаёт Average -3,9, Amplitude 0,5. Хлопки и щелчки дают амплитуду 0,5-1,1 и почти не влияют на среднее. Всяческие завывания дают амплитуду от 3 до 7 и среднее от -3,2 до -5,7, но большая часть ближе к -4.
