### ISSUE TITLE
Добавить класс генератора гармонического сигнала

### ISSUE THREAD

**Issue by RodionGork** [el-pths/nosov-dsp#4]
Подключим к нашей аудио-цепочке генератор синуса. Для этого нужно написать класс для замены Microphone.java (в той же папке). Назовем его SineGenerator.java.

По умолчанию пусть он генерирует синусоидальный сигнал с частотой 440 Гц и амплитудой 10000. (Потом придумаем параметризацию)

При этом генерировать нужно не мильон точек сразу, а по таймеру. Т.е. можно настроить например таймер на срабатывание 10 раз в секунду и выдавать по 4410 точек каждый раз... Общее количество значений (переданных дальше вызовом follower.nextValue) должно совпадать с SAMPLE_RATE.

Если все сделано правильно, программа должна печатать амплитуду раз в секунду, как и раньше, но амплитуда должна быть постоянной... Какой именно?

**Comment by NosovMihail** [comment]
Amplitude: 7078.462746341852

**Comment by RodionGork** [comment]
Нужно будет поправить стиль (см #8) а так все неплохо!
